FROM node:22-bookworm-slim

# Install latest chromium and fonts to support major charsets
# 'chromium' package in debian repo will automatically match the architecture (arm64/amd64)
RUN apt-get update \
    && apt-get install -y wget gnupg chromium \
    && apt-get install -y fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    && rm -rf /var/lib/apt/lists/*

# Create user
RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && mkdir -p /home/pptruser/.cache \
    && chown -R pptruser:pptruser /home/pptruser

# Tell Puppeteer to skip download and use installed chromium
ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

WORKDIR /app

COPY package.json .

# Install dependencies (will skip browser download because of env var)
RUN npm install

COPY server.js .
COPY entrypoint.sh .

RUN chmod +x entrypoint.sh \
    && chown -R pptruser:pptruser /app

USER pptruser

EXPOSE 3000

ENTRYPOINT ["./entrypoint.sh"]